FROM python:3.6-slim

RUN pip install --upgrade pip
RUN pip install flask WTForms==2.2.1
RUN pip install requests
RUN pip install pandas
RUN mkdir /opt/web
WORKDIR /opt/web
COPY . .
CMD python3 app.py